source 'https://github.com/cocoapods/specs.git'

platform :ios, '8.0'

project 'GTScrollNavigationBarExample'

def install_pods
  pod 'GTScrollNavigationBar', :path => '../'
end

target :GTScrollNavigationBarExample do
  install_pods
end

target :GTScrollNavigationBarTests do
  install_pods
  pod 'KIF', '~> 3.5'
  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
end
